[package]
name = "serum-swap"
version = "0.3.0-beta.1"
edition = "2018"
license = "Apache-2.0"
description = "Swap on the Serum DEX"
authors = ["Serum Foundation <foundation@projectserum.com>"]
repository = "https://github.com/project-serum/swap"

[lib]
crate-type = ["cdylib", "lib"]
name = "swap"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.11.0"
anchor-spl = "0.11.0"
solana-program = "1.7.4"